# QuantumLayer Resilience Fabric - golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
    - format: colored-line-number
  sort-results: true

linters:
  enable:
    # Default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional linters
    - bodyclose        # Check HTTP response body is closed
    - contextcheck     # Check context.Context usage
    - dupl             # Detect duplicate code
    - errname          # Check error naming conventions
    - errorlint        # Check error wrapping
    - exhaustive       # Check switch exhaustiveness
    - exportloopref    # Check loop variable capture
    - gochecknoinits   # No init functions
    - goconst          # Find repeated strings
    - gocritic         # Highly extensible linter
    - gocyclo          # Cyclomatic complexity
    - godot            # Check comment ending
    - gofmt            # Check formatting
    - goimports        # Check imports
    - goprintffuncname # Check printf-like function names
    - gosec            # Security checks
    - misspell         # Check spelling
    - nakedret         # No naked returns
    - nilerr           # Check nil error returns
    - noctx            # Check HTTP requests need context
    - prealloc         # Check slice preallocation
    - predeclared      # Check predeclared identifier shadowing
    - revive           # Drop-in replacement for golint
    - unconvert        # Remove unnecessary conversions
    - unparam          # Remove unused function parameters
    - whitespace       # Check whitespace

  disable:
    - depguard         # Too strict for now
    - funlen           # Function length limit
    - gochecknoglobals # No globals (too strict)
    - lll              # Line length limit
    - wsl              # Whitespace linter (too opinionated)

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment # Too noisy

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # Too strict
      - ifElseChain
      - octalLiteral
      - whyNoLint

  goimports:
    local-prefixes: github.com/quantumlayerhq/ql-rf

  gosec:
    excludes:
      - G104 # Audit errors not checked (we use errcheck)
      - G304 # File path provided as taint input (necessary for config)

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  prealloc:
    simple: true
    range-loops: true
    for-loops: true

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst

    # Exclude known issues in generated code
    - path: \.gen\.go
      linters:
        - all

    # Allow init functions in main packages
    - path: cmd/
      linters:
        - gochecknoinits

  max-issues-per-linter: 50
  max-same-issues: 5
