/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/overview/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard overview metrics */
        get: operations["getOverviewMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drift/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get drift summary */
        get: operations["getDriftSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List alerts */
        get: operations["listAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: uuid
         * @example 550e8400-e29b-41d4-a716-446655440000
         */
        UUID: string;
        /**
         * Format: date-time
         * @example 2025-12-04T10:30:00Z
         */
        Timestamp: string;
        ErrorResponse: {
            /** @description Error message */
            error: string;
            /** @description Error code for programmatic handling */
            code?: string;
        };
        /**
         * @description Direction of the metric trend
         * @enum {string}
         */
        TrendDirection: "up" | "down" | "neutral";
        MetricTrend: {
            direction: components["schemas"]["TrendDirection"];
            /**
             * @description Trend value (e.g., "+5%", "-2%")
             * @example +5%
             */
            value: string;
            /**
             * @description Comparison period
             * @example vs last 7 days
             */
            period: string;
        };
        MetricWithTrend: {
            /**
             * Format: int64
             * @description Current metric value
             */
            value: number;
            trend: components["schemas"]["MetricTrend"];
        };
        FloatMetricWithTrend: {
            /**
             * Format: double
             * @description Current metric value as percentage
             */
            value: number;
            trend: components["schemas"]["MetricTrend"];
        };
        /**
         * @description Infrastructure platform
         * @enum {string}
         */
        Platform: "aws" | "azure" | "gcp" | "vsphere" | "k8s";
        PlatformCount: {
            platform: components["schemas"]["Platform"];
            /** @description Number of assets on this platform */
            count: number;
            /**
             * Format: double
             * @description Percentage of total assets
             */
            percentage: number;
        };
        /**
         * @description Alert severity level:
         *     - critical: Immediate action required
         *     - high: Urgent attention needed
         *     - medium: Should be addressed soon
         *     - warning: Potential issue
         *     - low: Minor issue
         *     - info: Informational
         * @enum {string}
         */
        AlertSeverity: "critical" | "high" | "medium" | "warning" | "low" | "info";
        /**
         * @description Current alert status
         * @enum {string}
         */
        AlertStatus: "open" | "acknowledged" | "resolved";
        AlertCount: {
            severity: components["schemas"]["AlertSeverity"];
            /** @description Number of alerts with this severity */
            count: number;
        };
        Alert: {
            id: components["schemas"]["UUID"];
            orgId: components["schemas"]["UUID"];
            severity: components["schemas"]["AlertSeverity"];
            title: string;
            description: string;
            /** @enum {string} */
            source: "drift" | "compliance" | "connector" | "system";
            siteId?: components["schemas"]["UUID"];
            assetId?: components["schemas"]["UUID"];
            imageId?: components["schemas"]["UUID"];
            status: components["schemas"]["AlertStatus"];
            createdAt: components["schemas"]["Timestamp"];
            acknowledgedAt?: components["schemas"]["Timestamp"];
            acknowledgedBy?: components["schemas"]["UUID"];
            resolvedAt?: components["schemas"]["Timestamp"];
            resolvedBy?: components["schemas"]["UUID"];
        };
        AlertListResponse: {
            alerts: components["schemas"]["Alert"][];
            total: number;
            page: number;
            pageSize: number;
            totalPages: number;
        };
        /**
         * @description Type of activity event
         * @enum {string}
         */
        ActivityType: "info" | "warning" | "success" | "critical" | "patch" | "image" | "compliance" | "dr_test" | "ai_task";
        Activity: {
            id: components["schemas"]["UUID"];
            orgId: components["schemas"]["UUID"];
            type: components["schemas"]["ActivityType"];
            /** @description Brief description of the action */
            action: string;
            /** @description Detailed description */
            detail: string;
            userId?: components["schemas"]["UUID"];
            siteId?: components["schemas"]["UUID"];
            assetId?: components["schemas"]["UUID"];
            imageId?: components["schemas"]["UUID"];
            timestamp: components["schemas"]["Timestamp"];
        };
        /**
         * @description Drift status based on coverage percentage:
         *     - healthy: >= 90% coverage
         *     - warning: 70-89% coverage
         *     - critical: < 70% coverage
         * @enum {string}
         */
        DriftStatus: "healthy" | "warning" | "critical";
        DriftBySite: {
            /** @description Site identifier */
            siteId: string;
            /** @description Human-readable site name */
            siteName: string;
            /**
             * Format: double
             * @description Coverage percentage (0-100)
             */
            coverage: number;
            status: components["schemas"]["DriftStatus"];
        };
        DriftByEnvironment: {
            /** @description Environment name (production, staging, etc.) */
            environment: string;
            /** @description Total assets in environment */
            total: number;
            /** @description Compliant assets in environment */
            compliant: number;
            /**
             * Format: double
             * @description Compliance percentage
             */
            percentage: number;
        };
        DriftByAge: {
            /** @description Age range (e.g., "0-7 days", "8-14 days") */
            range: string;
            count: number;
            /** Format: double */
            percentage: number;
        };
        DriftSummaryResponse: {
            /** @description Total number of assets */
            totalAssets: number;
            /** @description Number of compliant assets */
            compliantAssets: number;
            /** @description Number of drifted assets */
            driftedAssets: number;
            /**
             * Format: double
             * @description Percentage of assets that are drifted
             */
            driftPercentage: number;
            /** @description Number of assets with critical drift */
            criticalDrift: number;
            /** @description Human-readable average drift age */
            averageDriftAge: string;
            byEnvironment: components["schemas"]["DriftByEnvironment"][];
            bySite: components["schemas"]["DriftBySite"][];
            byAge: components["schemas"]["DriftByAge"][];
        };
        OverviewMetrics: {
            fleetSize: components["schemas"]["MetricWithTrend"];
            driftScore: components["schemas"]["FloatMetricWithTrend"];
            compliance: components["schemas"]["FloatMetricWithTrend"];
            drReadiness: components["schemas"]["FloatMetricWithTrend"];
            platformDistribution: components["schemas"]["PlatformCount"][];
            alerts: components["schemas"]["AlertCount"][];
            recentActivity: components["schemas"]["Activity"][];
        };
    };
    responses: {
        /** @description Missing or invalid authorization */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOverviewMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Overview metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewMetrics"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    getDriftSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Drift summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriftSummaryResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
    listAlerts: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                severity?: components["schemas"]["AlertSeverity"];
                status?: components["schemas"]["AlertStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of alerts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalError"];
        };
    };
}
